### ISSUE TITLE
License for example code

### ISSUE THREAD

**Issue by SebAlbert** [ng-bootstrap/ng-bootstrap.github.io#2]
Can you add a license to the example code? I really like the "range" example for the Datepicker, and I think the code is quite concise (so I would like to just re-use it), but at the moment it seems there's no license associated with the example code.

**Comment by pkozlowski-opensource** [comment]
>  I really like the "range" example for the Datepicker

Glad you like it!

@SebAlbert in the footer of our demo page (https://ng-bootstrap.github.io) we've got: 

> Code licensed under MIT license conditions.

and

> Documentation licensed under CC BY 3.0

Our intention is to cover demo content under same conditions. 

Would you like to see additional / more precise licensing info anywhere in the source code / demo page?

**Comment by SebAlbert** [comment]
Oh, thanks and sorry I didn't see this, but even if I had, I might likely have thought it was merely refering to the Library itself. I was browsing for a license statement within the example code snippets and also here on this documentation repo (actually looking for the usual LICENSE file in the repo root).

If I understand this correctly, the example code is licensed MIT, not CC-BY 3.0 (which seems obvious since CC is not suited for software, but it may still be ambiguous since the example code could also be regarded part of the documentation).

So I think I can live with that, and it merely remains a suggestion to either
- clarify the footer like `Code (library and examples)` or similar
- add a LICENSE file to this repository
- add a comment in each of the example code snippets

(choose any subset, including the empty, of those suggestions, as you see fit)
