### ISSUE TITLE
Demo Datepicker select Today is not reflecting as expected

### ISSUE THREAD

**Issue by venkataramkishore** [ng-bootstrap/ng-bootstrap.github.io#3]
Thank you for your efforts, I am here to point out in Datepicker demo there are three buttons as follows:
Select today
To current month
To Feb 2013

try this sequence as below:
Click To Feb 2013
Click on Select today 

Expected : Datepicker should show current day along with year and month in blue box. 
Current: It does not effect anything

After i click on To current month button, then i can see actual selected day as expected.

Question: is this expected behavior or bug in binding issue?

**Comment by pkozlowski-opensource** [comment]
All the code, including demo site resides in https://github.com/ng-bootstrap/ng-bootstrap
Please re-open the issue in-there if this is still a problem.

We are not monitoring this repository for bug reports / PRs.
