### ISSUE TITLE
How to get source code?

### ISSUE THREAD

**Issue by wujun4code** [ng-bootstrap/ng-bootstrap.github.io#4]
I want to build a site for hosting docs. I like the style of https://ng-bootstrap.github.io.

How can I get the source code of the site, not the static HTMLs and css/js.

Thanks.

**Comment by pkozlowski-opensource** [comment]
It is here: https://github.com/ng-bootstrap/ng-bootstrap/tree/master/demo/src

**Comment by wujun4code** [comment]
Thanks. I got it.
