### ISSUE TITLE
Global toast stackblitz example returning 404

### ISSUE THREAD

**Issue by ceelsoin** [ng-bootstrap/ng-bootstrap.github.io#8]
By clicking on stackblitz example in https://ng-bootstrap.github.io/#/components/toast/examples
this link https://ng-bootstrap.github.io/stackblitzes/toast/global/stackblitz.html returning 404

**Comment by maxokorokov** [comment]
@ceelsoin thanks for reporting, it was fixed in https://github.com/ng-bootstrap/ng-bootstrap/pull/3375. Just haven't republished the site yet.

Workaround → open https://ng-bootstrap.github.io/stackblitzes/toast/howto-global/stackblitz.html
