### ISSUE TITLE
Example for vertical nav

### ISSUE THREAD

**Issue by Clashsoft** [ng-bootstrap/ng-bootstrap.github.io#9]
It would be nice to have an example on how to create a [vertical nav](https://getbootstrap.com/docs/4.4/components/navs/#vertical).

![Screenshot 2020-02-21 at 14 14 24](https://user-images.githubusercontent.com/4145923/75037443-77dc6380-54b4-11ea-94cb-e7c7e95bd865.png)

**Comment by maxokorokov** [comment]
You should look at bootstrap's examples for markup / flex / columns. 

On our side just use the `orientation="vertical"` from documentation here →https://ng-bootstrap.github.io/#/components/nav/api#NgbNav 

Anyway here is the stackblitz → https://stackblitz.com/edit/angular-elkcr8?file=app/nav-basic.html

I think having a demo for this would be an overkill...

**Comment by maxokorokov** [comment]
Also please open issues here → https://github.com/ng-bootstrap/ng-bootstrap

**Comment by Clashsoft** [comment]
My problem was that there is a bunch of stuff going on in your and bootstrap's examples, and piecing together what is needed for what and merging all the attributes is quite the challenge. Thanks for the stackblitz, though.

**Comment by maxokorokov** [comment]
@Clashsoft, good point, thank you for the feedback.

**Comment by maxokorokov** [comment]
Actually opened an issue for this one as it might be confusing, because `ngbNav` eats `flex-column` class if you try adding it manually and not using `[orientation]`...

https://github.com/ng-bootstrap/ng-bootstrap/issues/3615
